import { execFileSync, execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { chmodSync, mkdirSync, mkdtempSync, readFileSync, rmSync, existsSync, realpathSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createServer } from 'node:http';
const root=process.cwd(), temp=mkdtempSync(join(tmpdir(),'awgpt-package-e2e-')); let cli,server,bad;
const npm=process.platform==='win32'?'npm.cmd':'npm';
const run=async (a,o={})=>{ try { const r=await promisify(execFile)(process.execPath,[cli,...a],{cwd:temp,encoding:'utf8',timeout:10000,...o}); return r.stdout; } catch (e) { e.stdout=e.stdout??''; e.stderr=e.stderr??''; throw e; } };
const listen=s=>new Promise((resolve,reject)=>{s.once('error',reject); s.listen(0,'127.0.0.1',resolve);});
const closeServer=s=>s?.listening?new Promise((resolve,reject)=>s.close(e=>e?reject(e):resolve())):Promise.resolve();
try {
 const packed=execFileSync(npm,['pack','--json','--pack-destination',temp],{cwd:root,encoding:'utf8'}); const jsonStart=packed.lastIndexOf('\n['); const p=JSON.parse(jsonStart>=0?packed.slice(jsonStart+1):packed.slice(packed.indexOf('[')))[0];
 const packFiles=p.files??[]; const tarEntries=new Set(packFiles.map(f=>`package/${String(f.path??f).replaceAll('\\\\','/')}`)); const prefix=join(temp,'prefix');
 execFileSync(npm,['install','--prefix',prefix,'--ignore-scripts',join(temp,p.filename)],{cwd:root,stdio:'pipe'}); const installed=join(prefix,'node_modules','awgpt'); cli=join(installed,'dist','index.js');
 if(!(await run(['install','--help'])).includes('--source')) throw Error('packaged help missing lifecycle options'); const runHelp=await run(['run','--help']); if(!runHelp.includes('--project-root')||!runHelp.includes('--oracle-arg')) throw Error('packaged run help missing options'); const recoverHelp=await run(['recover','--help']); if(!recoverHelp.includes('--state')||!recoverHelp.includes('--action')) throw Error('packaged recover help missing options');
 const manifest=JSON.parse(readFileSync(join(installed,'install-manifest.json'),'utf8')); const included=manifest.include??[]; if(included.length<10) throw Error('manifest unexpectedly small'); for(const item of included) { const normalized=item.replaceAll('\\\\','/'); const exact=`package/${normalized}`; const prefix=`package/${normalized.replace(/\/$/,'')}/`; const pattern=new RegExp(`^${(exact).replace(/[.+^${}()|[\]\\]/g,'\\$&').replaceAll('*','.*')}$`); if(!tarEntries.has(exact) && ![...tarEntries].some(entry=>entry.startsWith(prefix)||pattern.test(entry))) throw Error(`manifest entry missing from npm pack: ${item}`); } const skills=[...new Set(included.filter(x=>x.startsWith('skills/')).map(x=>x.split('/')[1]))]; if(skills.length!==6) throw Error('skill manifest mismatch');
 const home=join(temp,'home'), install=JSON.parse(await run(['install','--agent-home',home])); if(!install.ok||install.count<6) throw Error('packaged install failed'); const receipt=JSON.parse(readFileSync(install.receipt,'utf8')); if(realpathSync(receipt.source_root)!==realpathSync(installed)) throw Error('wrong source_root');
 const project=join(temp,'project'); mkdirSync(project,{recursive:true}); const mission=join(project,'mission.md'); writeFileSync(mission,'# smoke\n'); const counters={initialize:0,open:0,ls:0};
 server=createServer((q,r)=>{let b='';q.on('data',c=>b+=c);q.on('end',()=>{const m=JSON.parse(b); const n=m.method; if(n==='initialize'){counters.initialize++;r.setHeader('mcp-session-id','e2e-session');r.setHeader('content-type','application/json');r.end(JSON.stringify({jsonrpc:'2.0',id:m.id,result:{protocolVersion:'2025-03-26',capabilities:{tools:{}},serverInfo:{name:'fake',version:'1'}}}));} else if(n==='notifications/initialized'){r.statusCode=202;r.end();} else {const name=m.params?.name; if(name==='open_workspace'){counters.open++;r.setHeader('content-type','application/json'); r.end(JSON.stringify({jsonrpc:'2.0',id:m.id,result:{content:[{type:'text',text:JSON.stringify({allowedRoots:[m.params.arguments.root]})}]}}));}else{counters.ls++;r.setHeader('content-type','application/json'); r.end(JSON.stringify({jsonrpc:'2.0',id:m.id,result:{content:[{type:'text',text:JSON.stringify({entries:[]})}]}}));}}})}); await listen(server); const ep=`http://127.0.0.1:${server.address().port}/mcp`;
 const fakeBase=join(temp,'oracle'), fake=process.platform==='win32'?fakeBase+'.cmd':fakeBase, cf=join(temp,'oracle-counter'); const fakeScript="#!/usr/bin/env node\nimport {appendFileSync,writeFileSync} from 'node:fs'; if(process.argv.includes('--version')) { console.log('0.17.1'); process.exit(0); } appendFileSync(process.env.E2E_COUNTER,JSON.stringify(process.argv.slice(2))+'\\n'); const i=process.argv.indexOf('--write-output'); if(i>=0) writeFileSync(process.argv[i+1],'TASK_OUTCOME: EXECUTED\\n'); console.log('TASK_OUTCOME: EXECUTED');"; writeFileSync(fakeBase+'.mjs',fakeScript); if(process.platform==='win32'){const nodePath=process.execPath.replaceAll('"','""'); writeFileSync(fake,`@echo off\r\n"${nodePath}" "%~dp0oracle.mjs" %*\r\n`);} else {writeFileSync(fake,fakeScript); chmodSync(fake,0o755);} const env={...process.env,E2E_COUNTER:cf};
 const pos=JSON.parse(await run(['run','--project-root',project,'--mission',mission,'--devspace-url',ep,'--oracle-command',fake],{env})); if(pos.state.task_outcome!=='EXECUTED'||counters.open!==1||counters.ls!==1||!existsSync(cf)) throw Error('positive E2E failed '+JSON.stringify({pos,counters,exists:existsSync(cf)}));
 const project2=join(temp,'project2'); mkdirSync(project2,{recursive:true}); const mission2=join(project2,'mission.md'); writeFileSync(mission2,'# smoke\n'); bad=createServer((q,r)=>{q.resume();q.on('end',()=>r.end(JSON.stringify({jsonrpc:'2.0',id:1,result:{content:[{type:'text',text:JSON.stringify({allowedRoots:[]})}]}})));}); await listen(bad); const nep=`http://127.0.0.1:${bad.address().port}/mcp`; const neg=JSON.parse(await run(['run','--project-root',project2,'--mission',mission2,'--devspace-url',nep,'--oracle-command',fake],{env})); await closeServer(bad); bad=null; if(neg.state.transport_status!=='failed'||existsSync(cf)===false) throw Error('negative gate failed');
 let rec; try { rec=JSON.parse(await run(['recover','--state',pos.statePath,'--action','live'])); } catch (e) { rec=JSON.parse(e.stdout); } const persisted=JSON.parse(readFileSync(join(pos.statePath,'..','workflow.json'),'utf8')); if(rec.session_authority!=='settled'||!['settled','attention_required'].includes(rec.status)||!Array.isArray(persisted.receipts)||!persisted.receipts.at(-1)?.receipt_id||!persisted.receipts.at(-1)?.output_sha256) throw Error('recovery evidence missing '+JSON.stringify(rec)); if(!JSON.parse(await run(['rollback','--agent-home',home])).ok) throw Error('rollback failed'); console.log(`package e2e ok (mcp_initialize=${counters.initialize}, mcp_open=${counters.open}, mcp_ls=${counters.ls}, oracle=1, negative=1, recovery=1)`);
} finally {await closeServer(server); await closeServer(bad); rmSync(temp,{recursive:true,force:true});}
